config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
  end

  resources :memberships do
    post 'confirm', on: :member
  end

  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  post 'places', to:'places#search'
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  get 'styles', to: 'styles#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  resources :styles, only: [:index, :show, :create, :destroy, :edit]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  # get 'kaikki_bisset', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to:'ratings#new'
  # post 'ratings', to: 'ratings#create'
  resources :ratings, only: %i[index new create destroy]
  resources :memberships, only: %i[index new create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :beer_club
  belongs_to :user, optional: true
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @beer_clubs = BeerClub.all
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.update_attribute(:confirmed, false)

    if @membership.save
      if current_user.memberships.find_by(beer_club_id: params[:membership][:beer_club_id]).nil?
        current_user.memberships << @membership
        redirect_to beer_club_path @membership.beer_club_id, flash[:notice] = "#{current_user.username} welcome to the club!"
      end
    else
      @beer_clubs = BeerClub.all
      render :new
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @user = User.find_by id: @membership.user_id
    @club = BeerClub.find_by id: @membership.beer_club_id
    @membership.destroy
    flash[:notice] = "Membership in #{@club.name} has ended."
    redirect_to user_path(@user)
  end

  def confirm
    membership = Membership.find(params[:id])
    membership.update_attribute :confirmed, true

    redirect_to breweries_path, notice: "Membership confirmed!"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def membership_params
    params.require(:membership).permit(:user_id, :beer_club_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :name) %>
  <%= form.submit 'Join a club' %>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"></p>

<h1>Memberships</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Beer club</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user_id %></td>
        <td><%= membership.beer_club_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path, class:'btn btn-primary' %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path, class:'btn btn-primary' %>

app/views/memberships/show.html.erb
<p id="notice"></p>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<p>
  <strong>Beer club:</strong>
  <%= @membership.beer_club_id %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>