config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
  end

  resources :memberships do
    post 'confirm', on: :member
  end

  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  post 'places', to:'places#search'
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  get 'styles', to: 'styles#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  resources :styles, only: [:index, :show, :create, :destroy, :edit]
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  # get 'kaikki_bisset', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to:'ratings#new'
  # post 'ratings', to: 'ratings#create'
  resources :ratings, only: %i[index new create destroy]
  resources :memberships, only: %i[index new create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships

  def member?(user)
    users.each do |usr|
      if user == usr
        return true
      end
    end
    false
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_admin_rights, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json

  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when 'name' then @beer_clubs.sort_by(&:name)
                  when 'founded' then @beer_clubs.sort_by(&:founded)
                  when 'city' then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @pending_users = @beer_club.memberships.all.where(confirmed: false)

    if current_user && @beer_club.users.find_by_id(current_user.id).nil?
      @membership = Membership.new
      @membership.beer_club = @beer_club
    else
      @membership = Membership.find_by user_id: current_user.id
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save

        @beer_club.users << current_user
        @beer_club.memberships.find_by_user_id(current_user.id).update_attribute(:confirmed, true)

        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!--
  <div class="form-group">

  <label for="name">Name</label>
  <input type="name" class="form-control" id="name">

  </div>

  <div class="form-group">

  <label for="founded">Founded</label>
  <input type="founded" class="form-control" id="founded">

  </div>

  <div class="form-group">

  <label for="city">City</label>
  <input type="city" class="form-control" id="city">

  </div>

  <button type="submit" class="btn btn-primary">Create Beer Club</button>
-->
<div class="form-group">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :founded %>
    <%= form.number_field :founded, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"></p>

<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
      <td><%= link_to beer_club.name %></td>
      <td><%= beer_club.founded%></td>
      <td><%= beer_club.city%></td>
        <td><%= link_to 'Show', beer_club %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club) if current_user%></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' } if current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Beer Club', new_beer_club_path, class:'btn btn-primary' if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"></p>

<p>
  <strong>Name:</strong>
  <%= @beer_club.name %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

<p>
  <strong>Members:</strong>
  <%= @beer_club.users.each do |user| %>
    <% if @beer_club.memberships.find_by_user_id(user.id).confirmed %> 
  <%= link_to user do%>
  <p><%= user.username%></p>
  <% end %>
  <% end %>
  <% end %>
</p>


<% if current_user %>

<% if @beer_club.member?(current_user) and @beer_club.memberships.find_by_user_id(current_user.id).confirmed  %>
<p>
  <strong>Outstanding applications:</strong>
  <% @pending_users.each do |u| %>
    <p> <%= User.find_by_id(u.user_id).username %> 
    <%= link_to "Confirm", confirm_membership_path(u.id), method: :post, class: "btn btn-primary" %>
    </p>
    <% end %>
</p>
<% end %>

<%if @beer_club.users.find_by_id(current_user.id).nil? %>

<%= form_for(@membership) do |f| %>
 <%= f.hidden_field :beer_club_id %>
 <%= f.submit value:"join the club", class:"btn btn-primary"  %>
<% end %>
<%else%>
<% if @beer_club.member?(current_user) and @beer_club.memberships.find_by_user_id(current_user.id).confirmed  %>
<%= form_for(@membership, method: "delete") do |f| %>
 <%= f.hidden_field :beer_club_id %>
 <%= f.submit value: "end the membership", class:"btn btn-primary"  %>
<% end %>
<% end %>
<% end %>
<% end %>

<%= link_to 'Edit', edit_beer_club_path(@beer_club), class:'btn btn-primary' %> |
<%= link_to 'Back', beer_clubs_path, class:'btn btn-primary' %>